### ISSUE TITLE
rackup when configure web_apps default

### ISSUE THREAD

**Issue by carlhoerberg** [trinidad/trinidad#66]
trinidad won't start with the following config:

```

---
  rackup: 'config.ru'
  web_apps: 
    default: 
      extensions: 
```

```

2012-04-03 17:29:50 INFO: An exception happened during JRuby-Rack startup
No such file to load -- /Users/carl/code/trinidad_extension_bug/config/environment.rb
--- System
jruby 1.6.7 (ruby-1.9.2-p312) (2012-02-22 3e82bc8) (Java HotSpot(TM) Client VM 1.6.0_29) [darwin-i386-java]
Time: 2012-04-03 19:29:50 +0200
Server: Apache Tomcat/7.0.23
jruby.home: /Users/carl/.rvm/rubies/jruby-1.6.7

--- Context Init Parameters:
jruby.compat.version = 1.9.2
jruby.initial.runtimes = 1
jruby.max.runtimes = 5
jruby.min.runtimes = 1
public.root = /public
rails.env = development
rails.root = /

--- Backtrace
LoadError: No such file to load -- /Users/carl/code/trinidad_extension_bug/config/environment.rb
              load at org/jruby/RubyKernel.java:1068
  load_environment at file:/Users/carl/.rvm/gems/jruby-1.6.7/gems/jruby-rack-1.1.4/lib/jruby-rack-1.1.4.jar!/jruby/rack/rails.rb:61
  load_environment at file:/Users/carl/.rvm/gems/jruby-1.6.7/gems/jruby-rack-1.1.4/lib/jruby-rack-1.1.4.jar!/jruby/rack/rails.rb:191
            (root) at <script>:1
```

but this config works:

```

---
  web_apps: 
    default: 
      rackup: 'config.ru'
      extensions: 
```

and of course this:

```

---
  rackup: 'config.ru'
```
