### ISSUE TITLE
errors from sqlite jdbc on re-deploys

### ISSUE THREAD

**Issue by kares** [trinidad/trinidad#94]
setup Rails 3.2.8 

database.yml

``` yml
development:
  adapter: sqlite3
  database: db/development.sqlite3

production:
  adapter: sqlite3
  database: db/production.sqlite3
```

Gemfile

``` ruby
gem 'activerecord-jdbcsqlite3-adapter'
gem 'jruby-openssl'
```

after a (restart) re-deploy prints on STDERR :

**java.lang.UnsatisfiedLinkError: Native Library /tmp/sqlite-3.7.2-libsqlitejdbc.so already loaded in another classloader**
